apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banking
  namespace: banking
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: banking.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: banking-frontend
                port:
                  number: 80
